FROM cloudsuite/java:openjdk7-aarch64

# Install dependencies
RUN apt-get update -y && apt-get install -y --no-install-recommends \
      libblas3 \
      libgfortran3 \
      liblapack3 \
      curl \
&& rm -rf /var/lib/apt/lists/*

ENV SPARK_VERSION 2.1.0
ENV HADOOP_VERSION 2.7
ENV MIRROR  https://d3kbcqa49mib13.cloudfront.net/
ENV SPARK_HOME /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}

# Install Spark
RUN set -x \
    && curl ${MIRROR}spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz | tar -xzC /opt \
    && export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::") \
    && apt-get purge -y --auto-remove ${BUILD_DEPS}

COPY files /root/

# Expose Spark ports
ENV SPARK_MASTER_PORT 7077
ENV SPARK_WEBUI_PORT 8080
EXPOSE ${SPARK_MASTER_PORT} ${SPARK_WEBUI_PORT}

ENTRYPOINT ["/root/entrypoint.sh"]

