FROM cloudsuite/debian:base-os

RUN apt-get update -y && apt-get install -y --no-install-recommends openjdk-11-jdk-headless \
        && rm -rf /var/lib/apt/lists/*
# TODO: Fix this link for other architectures.
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-riscv64/
